# @lc app=leetcode id=389 lang=python3
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (58.39%)
# Likes:    1466
# Dislikes: 325
# Total Accepted:    278.3K
# Total Submissions: 475.9K
# Testcase Example:  '"abcd"\n"abcde"'
#
# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
#
# Return the letter that was added to t.
#
#
# Example 1:
#
#
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
#
#
# Example 2:
#
#
# Input: s = "", t = "y"
# Output: "y"
#
#
# Example 3:
#
#
# Input: s = "a", t = "aa"
# Output: "a"
#
#
# Example 4:
#
#
# Input: s = "ae", t = "aea"
# Output: "a"
#
#
#
# Constraints:
#
#
# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lower-case English letters.
#
#
#

# @lc tags=hash-table;bit-manipulation

# @lc imports=start
from imports import *

# @lc imports=end

# @lc idea=start
#
# 给定两个字符串，求多出的一个字符。
#
# @lc idea=end

# @lc group=

# @lc rank=


# @lc code=start
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        d = defaultdict(int)
        for c in s:
            d[c] += 1
        for c in t:
            d[c] -= 1
            if d[c] < 0:
                return c
        pass


# @lc code=end

# @lc main=start
if __name__ == '__main__':
    print('Example 1:')
    print('Input : ')
    print('s = "abcd", t = "abcde"')
    print('Exception :')
    print('"e"')
    print('Output :')
    print(str(Solution().findTheDifference("abcd", "abcde")))
    print()

    print('Example 2:')
    print('Input : ')
    print('s = "", t = "y"')
    print('Exception :')
    print('"y"')
    print('Output :')
    print(str(Solution().findTheDifference("", "y")))
    print()

    print('Example 3:')
    print('Input : ')
    print('s = "a", t = "aa"')
    print('Exception :')
    print('"a"')
    print('Output :')
    print(str(Solution().findTheDifference("a", "aa")))
    print()

    print('Example 4:')
    print('Input : ')
    print('s = "ae", t = "aea"')
    print('Exception :')
    print('"a"')
    print('Output :')
    print(str(Solution().findTheDifference("ae", "aea")))
    print()

    pass
# @lc main=end